site_name: 'Le YouTube de demain est-il libre ?'
site_description: "Le YouTube de demain est-il libre ? Google continuera-t-il de dicter l'avenir des créateurs ? - Livre blanc sur le partage de vidéo"
site_author: Raphaël Cerveaux
site_url: https://sundowndev.github.io/livre-blanc-video/

theme:
  name: 'material'
  icon:
    logo: material/feather
  palette:
    primary: blue
    accent: blue
  font:
    text: Nunito
    code: Roboto Mono
  features:
    - tabs
    - instant

nav:
  - "Introduction":
    - "Résumé": index.md
    - "Contribuer": contribute.md
  - "Le partage de vidéo, aujourd'hui":
    - "Modèle économique": today/business-model.md
    - "En communauté": today/community.md
    - "Écologie": today/ecology.md
    - "Opportunités": today/opportunities.md
    - "Transparence, vie privée & éthique": today/privacy.md
  - "Le partage de vidéo, demain":
    - "Les alternatives": tomorrow/alternatives.md
    - "Modèle économique": tomorrow/business-model.md
    - "En communauté": tomorrow/notfound.md
    - "Écologie": tomorrow/notfound.md
    - "Opportunités": tomorrow/notfound.md
    - "Transparence, vie privée & éthique": tomorrow/notfound.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/sundowndev/livre-blanc-video

markdown_extensions:
  - toc:
      permalink: true

plugins:
  - search
  - minify:
      minify_html: true

# Repository
# repo_name: sundowndev/livre-blanc-video
# repo_url: https://github.com/sundowndev/livre-blanc-video
# edit_uri: 'https://github.com/sundowndev/livre-blanc-video/edit/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2020 Raphaël Cerveaux'
